# Generated by Django 2.0.2 on 2018-05-19 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idm', '0003_auto_20180512_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='faces/')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='face',
            field=models.FileField(null=True, upload_to='myface/', verbose_name='Upload Face'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='face',
            name='userr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usr', to=settings.AUTH_USER_MODEL),
        ),
    ]
