# Generated by Django 2.0.2 on 2018-05-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idm', '0004_auto_20180519_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_face',
            field=models.FileField(null=True, upload_to='profile/'),
        ),
    ]
